### ISSUE TITLE
Find a way to build Map from slices of anonymous data (Vec<u8>) without copy.

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#11]
Would it be possible to make FstData public?

**Comment by BurntSushi** [comment]
Could you please describe the problem you're trying to solve and how making `FstData` public would help?

**Comment by fulmicoton** [comment]
... And I'm quite new to rust so I might absolutely be doing something wrong.

In a nutshell, I'm trying to write a search engine. The term dictionary is using the fst library. I'd like to have the equivalent of Lucene's RamDirectory (mostly for tests) as well MMapDirectory. 

I am not exactly sure how to design this, but I like your FstData enum solution. The problem is that I cannot build a similar structure in my project because the Fst public constructors only offer Path or `Vec<u8>`.

**Comment by BurntSushi** [comment]
Did you miss the `from_mmap` function? https://github.com/BurntSushi/fst/blob/master/src/raw/mod.rs#L299 If you have an `Mmap` (from the `memmap` crate), then you can get a `MmapReadOnly` with `MmapReadOnly::from(mmap)` because of this impl: https://github.com/BurntSushi/fst/blob/master/src/raw/mmap.rs#L70

I think the bigger picture here is that you don't get any additional power with respect to construction by having `FstData` public because all ways of building an `FstData` value are exposed via constructors on the `Fst` type.

**Comment by fulmicoton** [comment]
But from_mmap makes it possible to build a `Fst` but not a `fst::Map` as the field is private (`pub struct Map(raw::Fst);`) and there is no constructor function to built a `Map` from an `Fst`...

Here is a more accurate/specific use case, that should cover all of my needs.

I want to use the fst to build a map that goes `&[u8]` to `&[u8]`. It is stored in a file as follows. The starts first contains the fst. the values are serialized sequentially in the second part of the file. The fst index the keys to the offset of the associated value entry in the second part of the file. This is stored in the same file to avoid having two many file descriptors for instance.

I want the map to work off either a Mmapped file, but also on a `Vec<u8>`.

The mmap object already include some slicing functionality, but I don't think it is currently possible to build the fst off a section of a `Vec<u8>` without copying the actually section.

**Comment by BurntSushi** [comment]
Try `Map::from(some_raw_fst)`. It's important to pay attention to the generic impls. :)

Even if those impls didn't exist, exposing just FstData wouldn't fix the problem. There would also need to be a new constructor

**Comment by BurntSushi** [comment]
Hmm. Does that impl not exist? Could have sworn i added it. Time for me to eat crow i guess!

I think I'd be happy exposing a way to get a map from a raw fst.

**Comment by fulmicoton** [comment]
That would be awesome... This will solve only half of my problem (building fst:Map from my mmaps), and I don't think the second (build fst::Map from something anonymous memory without any copy) can be addressed without introducing a lot of stuff. I can work with tempfiles for the moment.

**Comment by BurntSushi** [comment]
@fulmicoton OK, so I'm still trying to grok what you want to do and why you think you need to copy a `Vec<u8>`. One thing you can do is supply a `Vec<u8>` to a `MapBuilder`, and when you're done building it, you can ask for your original `Vec<u8>` back. There is an example of that here: http://burntsushi.net/rustdoc/fst/struct.MapBuilder.html#example-build-in-memory --- The relevant bits are:

```rust
let mut build = MapBuilder::memory();
build.insert("bruce", 1).unwrap();
build.insert("clarence", 2).unwrap();
build.insert("stevie", 3).unwrap();
let bytes = build.into_inner().unwrap();
```

Note that `bytes` has type `Vec<u8>` in this example. If you wanted to start with your own `Vec<u8>`, then this also works:

```rust
let my_vec = vec![];
let mut build = MapBuilder::new(my_vec);
build.insert("bruce", 1).unwrap();
build.insert("clarence", 2).unwrap();
build.insert("stevie", 3).unwrap();
let bytes = build.into_inner().unwrap();
```

This example moves `my_vec` into the builder and then moves it back out again once construction is done. `my_vec` doesn't have to be empty. This is all generic so all you actually need is anything that implements the `io::Write` trait.

Now, what you *can't* do (I think) is write both things at once in a single loop without doing some kind of copying at the end. The issue here is that you don't actually know how big the FST will be in memory, so you can't create both the FST and your term mapping at the same time without having to move either one of them after the process is done. This is quite simply a fundamental limitation of FST construction---there's nothing you can do about it. (It's probably bad to do this anyway, especially to a single file, since it won't be writing sequentially, which is a key reason why FST construction is as fast as it is.)

With that said, it seems like you should be able to write your term mapping first, which should produce stable offsets into a `Vec<u8>`. You can then write your FST into that same `Vec<u8>` after the term map with the right offsets. This requires two loops through the data, but you shouldn't have to copy anything.

If this doesn't help you, then that means I've misunderstood what you're trying to do, in which case, could you show in rough pseudo code what you're trying to do?

**Comment by fulmicoton** [comment]
Yes I understand this is very confusing. This ticket ends up spawning into many difffernt tickets.

I have no problem with the writing. That's reading that I have problem with.
Once I got my `Vec<u8>` written, how do I get an fst mapped over the proper segment? My vector contains the value that I need access to, and the fst mapping to the offsets.

To build the fst map I can only give it ownership of the whole vector.
`MmapReadOnly`, on the other hand is awesome because 
a) it is in fact wrapping a reference counter, so I can keep "share ownership" (not sure it is the correct term) of my mmap.
b) it is sliceable, so I can have the fst work on only the relevant part of the data.

Here is what the writer could look like.

`pub struct FstMapBuilder<W: Write, V: BinarySerializable> {
    fst_builder: MapBuilder<W>,
    data: Vec<u8>,
    _phantom_: PhantomData<V>,
}

impl<W: Write, V: BinarySerializable> FstMapBuilder<W, V> {

    fn new(w: W) -> io::Result<FstMapBuilder<W, V>> {
        let fst_builder = try!(MapBuilder::new(w).map_err(convert_fst_error));
        Ok(FstMapBuilder {
            fst_builder: fst_builder,
            data: Vec::new(),
            _phantom_: PhantomData,
        })
    }

    fn insert(&mut self, key: &[u8], value: &V) -> io::Result<()>{
        try!(self.fst_builder
            .insert(key, self.data.len() as u64)
            .map_err(convert_fst_error));
        value.serialize(&mut self.data);
        Ok(())
    }

    fn close(self,) -> io::Result<W> {
        let mut file = try!(self.fst_builder
                 .into_inner()
                 .map_err(convert_fst_error));
        let footer_size = self.data.len();
        file.write_all(&self.data);
        (footer_size as u32).serialize(&mut file);
        Ok(file)
    }
}`


For the reader, if I am using Mmap I can write

`
pub struct FstMap<V: BinarySerializable> {
    fst_index: fst::Map,
    values_mmap: MmapReadOnly,
    _phantom_: PhantomData<V>,
}


impl<V: BinarySerializable> FstMap<V> {
    pub fn open(file: &File) -> io::Result<FstMap<V>> {
        let mmap = try!(MmapReadOnly::open(&file));
        let mut cursor = Cursor::new(unsafe {mmap.as_slice()});
        try!(cursor.seek(io::SeekFrom::End(-4)));
        let footer_size = try!(u32::deserialize(&mut cursor)) as  usize;
        let split_len = mmap.len() - 4 - footer_size;
        let fst_mmap = mmap.range(0, split_len);
        let values_mmap = mmap.range(split_len, mmap.len() - 4);
        let fst = try!(fst::raw::Fst::from_mmap(fst_mmap).map_err(convert_fst_error));
        Ok(FstMap {
            fst_index: fst::Map::from(fst),
            values_mmap: values_mmap,
            _phantom_: PhantomData,
        })
    }

    pub fn get<K: AsRef<[u8]>>(&self, key: K) -> Option<V> {
        self.fst_index
            .get(key)
            .map(|offset| {
                let buffer = unsafe { self.values_mmap.as_slice()};
                let mut cursor = Cursor::new(&buffer[(offset as usize)..]);
                V::deserialize(&mut cursor).unwrap()
            })
    }
}`

But if I wrote that in a `Vec<u8>`, I believe there is no way for me to make this work without copying the `Vec<u8>`.

**Comment by BurntSushi** [comment]
I get it now. You're right, this is a problem. I remember grappling with it now. At one point, I had `&[u8]` as a variant in `FstData`, which would enable your use case since you can slice it. The lifetime however introduced some serious problems elsewhere. (I can't remember if it made the code hard to write or if it actually ran into something that conflicted with the higher rank trait bounds being used in streams.)

One way to fix this is to introduce a new variant that wraps `Arc<Vec<u8>>`, except the `Vec<u8>` probably needs to be a `VecSlice<u8>` so that you can cause it to use the right offsets.

I agree that this is a problem worth solving. If you want to take a crack at a PR, that'd be cool.

**Comment by fulmicoton** [comment]
Yes I can see 2 or 3 solutions to this problem, all equally adding in complexity and unperfect.
I can live with working only with files for the moment, but I might send you a PR if I feel the urge for a proper RAMDirectory. In that case, I'll double check with you in advance that the big line of the implementation are ok.

Should I send you a PR for the implementation of `From<Fst>` for `Map`?

**Comment by fulmicoton** [comment]
I renamed the issue. It made very little sense.

**Comment by BurntSushi** [comment]
> Should I send you a PR for the implementation of From<Fst> for Map?

That'd be much appreciated. If you don't, I'll do it the next time I have a free moment, so up to you!

**Comment by fulmicoton** [comment]
Is this what you had in mind? 

https://github.com/fulmicoton/fst/commit/8dc24c2ef430c8433f00e752111b72c6aa52bf85

**Comment by BurntSushi** [comment]
@fulmicoton That is pretty close, yes. I have some nits on it, but if you submit a PR, we can try to get it merged.

**Comment by BurntSushi** [comment]
@fulmicoton I think I've fixed this in: https://github.com/BurntSushi/fst/commit/d40a65be9d813186d5de49c40931c1ad31ae7ba8

**Comment by fulmicoton** [comment]
@BurntSushi  Awesome! I will use that.

**Comment by fulmicoton** [comment]
Thanks. It worked like a charm.
