### ISSUE TITLE
API for re-using allocation across several searches

### ISSUE THREAD

**Issue by matklad** [BurntSushi/fst#110]
Current stream API allows to re-use allocation during a single search, which helps a lot when you have a big FST, and want to run a single query. However, I've found myself in a situation where I have a tiny FST and a large number of queries. In this situation, each query allocates scratch space separately, and, if I am not mistaken, current API does not allow me to re-use this space between queries. 

My specific use case is this:

I have a number (dozens) of root paths, and a lot (tens of thousands) file paths. For each file path, I want to find a root path where it belongs (find the longest string which is also a prefix of the query). My solution is to build an `fst::Map` over root paths, and run many prefix queries over it.

[Source](https://github.com/rust-analyzer/rust-analyzer/blob/a34f79b17412f83242283fae6e7a6275b4056611/crates/vfs/src/file_set.rs#L60-L68).

**Comment by BurntSushi** [comment]
Right, yeah, there is no API to amortize allocation. In principle I'm not opposed to adding it, but worry about the API complexity. If it's just another method on the various FST types in this crate, and the implementation can stay DRY, then I'd be okay with a PR adding it assuming we could at least satisfy (1) below. (2) and (3) below are more situation dependent.

With that said, I have a few concerns:

1. Whether a meaningful performance difference can be measured. Traversing the FST isn't exactly the cheapest of things and it's not clear to me that amortizing allocation would meaningfully help. I _think_ `BTree{Set,Map}` has to do largely the same thing for example, and there are no APIs there to amortize allocation. (But someone should check me on that.)
2. It seems to me like whether you had a big or a tiny FST is a red herring. What really matters is the depth of the FST, right?
3. If you really do have a tiny FST, then you're kinda not in the wheelhouse of this crate. The wheelhouse of this crate are huge sets or maps precisely because of its compression. But if you have tiny sets, then the compression is only going to hurt you: the space savings probably doesn't matter, so you'll end up paying to decompress the FST while traversing it for no good reason. FST searches are fast, but they are never going to be as fast as a simple in-memory trie, for example. Although, I of course understand the simplicity of just using an FST if you're already using it for other things, instead of building a new trie data type. But that to me would suggest that you don't care as much about lookup time, because you're undoubtedly paying a lookup time penalty. So amortizing allocation at that point seems a bit weird.

**Comment by matklad** [comment]
Hm, 1. is an extremely good point! I've applied a quick patch to reuse allocations, and, for my use case:

* I indeed observe the number of allocations going down (so, that patch is correct in this sense)
* I don't observe meaningful performance improvement, which might be attributed to either allocation not being a hot path of fst, or to fst not being a hot path of code I am measuring (I did "end2end" style measurement). Specifically, looks like my surrounding code does a liner amount of allocations anyway.

Additionally, I've noticed that re-using allocations won't be too easy -- the stack of states is parametrized by the lifetime, and to really re-use it we need a function like `fn clear<'a, 'B>(xs: Vec<Foo<'a>>) -> Vec<Foo<'b>>`, which, while sound, isn't implementable in safe Rust I think. I had to do some unsound lifetime transmutes to get the numbers.

And yeah, my original motivation was "write less code", rather than "write faster code", there's indeed a lot of more promising optimization venues in my case, than amortising allocations.

>I think BTree{Set,Map} has to do largely the same thing for example

`std::collection::BTreeMap` stores parent pointers in nodes, so it doesn't need an explicit stack for traversal. 

I guess this all together means that this issue isn't really worth action on, thanks for asking the right questions :)

**Comment by BurntSushi** [comment]
> `std::collection::BTreeMap` stores parent pointers in nodes, so it doesn't need an explicit stack for traversal.

Hmm, I see. The btree code appears to have gotten a lot more complex since I last looked at it. My memory might be bad too. :)
