### ISSUE TITLE
Dynamic add new elements to Set

### ISSUE THREAD

**Issue by diegobernardes** [BurntSushi/fst#18]
Reading the [docs](http://burntsushi.net/rustdoc/fst/struct.Set.html) say that a Set:

> Once constructed, a Set can never be modified.

There is any work around to this? I'm learning rust now and doing a little search engine for fun, one of the requirements is to add new elements and/or update older ones.
If everytime i need to complete rebuild the set just to add a element, gonna get very slow.

Thanks!

**Comment by BurntSushi** [comment]
Have you [read the blog post the covers the underlying data structure and construction algorithm](http://blog.burntsushi.net/transducers/)? Immutability is a fundamental aspect of this particular data structure. There are of course other approaches (*in theory*, from the literature) that would allow one to build an FST in an online manner, but the set of trade offs employed are completely different, and would probably result in worse scaling properties.

If you're just building a search engine for fun and need a quick inverted index, then I'd probably just recommend using a prefix trie. Using this crate when mutation is required is a big endeavor because you'll need to figure out a way to amortize the cost of mutation. You're right to point out that "building a new FST for every key added" is too expensive, and of course that isn't how you should do it. Instead, you'll need to maintain *multiple* FSTs at once and apply some sort of criteria for merging them when you get too many.

**Comment by BurntSushi** [comment]
> Instead, you'll need to maintain multiple FSTs at once and apply some sort of criteria for merging them when you get too many.

It would be interesting to build an additional crate that tried to handle some of this process for you, but I'm not quite convinced there is a universally good approach to it. I personally need more experience with it before I can conceive of something more general purpose. For now, you'll have to hand roll it. (This crate does already provided a very fast way to merge multiple FSTs in a single pass using set union operations.)

**Comment by diegobernardes** [comment]
Thanks @BurntSushi gonna read your post and more about this data structure.
