### ISSUE TITLE
Implement From<Arc<Mmap>> for MmapReadOnly

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#33]
My use case is to have a Mmap cache, and creating MmapReadOnly by promoting `std::sync::Weak<Mmap>`.

**Comment by fulmicoton** [comment]
PR here https://github.com/BurntSushi/fst/pull/34

**Comment by BurntSushi** [comment]
Given my comments in #34, is there any way this could work if we removed the `memmap` crate from the public API of the `fst` crate? I ask because publishing other crate types through another crate essentially ties your public API to the public API of another crate, which reduces flexibility.

I imagine doing such a thing would probably not be very nice for you, especially if you are (understandably) using `Mmap` everywhere.

**Comment by fulmicoton** [comment]
Yes in the current state, removing `memmap` from the public API will be a problem for `tantivy`.

Alternatively, what about making `Fst` generic over a trait that would replace`FstData` ?

**Comment by BurntSushi** [comment]
You are right to point out the trait approach. That is probably the correct answer to my concern. The extra type parameter everywhere would suck, which is why I went with the enum. But then we wind up with this problem. Not sure which is worse. :-)

**Comment by fulmicoton** [comment]
There are probably ways to keep the public API relatively clean (defaulting the generic type to an enum equivalent to the one you have today?)

The internal implementation will suffer from the suckiness though.

**Comment by BurntSushi** [comment]
> There are probably ways to keep the public API relatively clean (defaulting the generic type to an enum equivalent to the one you have today?)

Hmm, possible...

> The internal implementation will suffer from the suckiness though.

FWIW, I'm more or less OK with that.
