### ISSUE TITLE
Prefer using an Arc<[u8]> instead of an Arc<Vec<u8>>

### ISSUE THREAD

**Issue by Kerollmops** [BurntSushi/fst#97]
[In a previous comment](https://github.com/BurntSushi/fst/pull/95#pullrequestreview-362934054) it seemed you were ready to probably introduce breaking changes to the library.

I found out that an fst (and thus a set and a map) can be [created from shared bytes](https://docs.rs/fst/0.3.5/fst/raw/struct.Fst.html#method.from_shared_bytes), those are represented by an `Arc` of `Vec<u8>`, I was wondering why you chose to use this type instead of an `Arc<[u8]>`.

One of the advantage of an `Arc<[u8]>` is that it can be used every where `AsRef<[u8]>` is needed, an `Arc<Vec<u8>>` doesn't implement this trait.

The only advantage I see in this choice is for performance reason that will be rarely triggered: constructing an `Arc<Vec<u8>>` from an existing vec is cheaper as it will not copy the entirety of the bytes, [`Arc<[u8]>` does](https://doc.rust-lang.org/src/alloc/sync.rs.html#852-861).

I will stop bothering you, and let you work on more interresting features now :)
I just wanted to make sure to break things when possible and clean the library a little bit more if this makes any sense, of course.

**Comment by BurntSushi** [comment]
This is a great issue, thanks. If you have other suggestions for breaking changes, please share them. Now is a good time. Unfortunately, the way I do development in FOSS isn't terribly conducive to collaboration because I have a terrible time context switching. So I end up doing things in short spurts.

As for why I chose `Arc<Vec<u8>>`, I don't know. I added it about 3.5 years ago. Did `Arc` even supports DSTs back then? Ah okay... It looks like they were [added in the Rust 1.2 release](https://github.com/rust-lang/rust/blob/master/RELEASES.md#highlights-4). So by mid 2016 (when `Arc<Vec<u8>>` was added), `Arc<[u8]>` had been available for a year. It's possible that I just didn't consider it at all, or didn't even know about it.

... but looking at std, I actually don't see an easy (and safe) way to _build_ an `Arc<[u8]>`. Do you? Ah, I see now, there is a [`impl From<Vec<T>> for Arc<[T]>`](https://doc.rust-lang.org/src/alloc/sync.rs.html#2021). But that wasn't introduced until Rust 1.21, which came out in mid 2017, well after I added the `Arc<Vec<u8>>` API. So that probably explains it (combined with me probably not even considering it at all).

The extra copy does indeed seem unfortunate, particularly given that FSTs tend to be quite large.

With all that said, my plan at the moment is to adopt what tantivy's fork of `fst` did: add a type parameter that satisfies `AsRef<[u8]>`. That should let you use whatever type you want. I have resisted doing this in the past because I _really_ do not want to thread a type parameter everywhere. But tantivy apparently needs it and this has been a pain point for others, e.g., in #92.

Does this assuage your concern?

**Comment by Kerollmops** [comment]
No worries, that was just the only reason (IIRC) I forked the library and step back because it is not pleasant to work with a fork.

You said that there were no safe way to construct an `Arc<[u8]>` from a `Vec<u8>` before 1.21, but [`From<&[u8]>` exists since 1.21](https://doc.rust-lang.org/std/sync/struct.Arc.html#impl-From%3C%26%27_%20%5BT%5D%3E).

Anyway, you will change the API to make it better, so don’t take my comment into account.

Thank you for your work :)

PS: will you fix #92 to make it safe to read an FST from any slice lifetime?

**Comment by BurntSushi** [comment]
> You said that there were no safe way to construct an Arc<[u8]> from a Vec<u8> before 1.21, but From<&[u8]> exists since 1.21.

Yes? That's also when the From impl for Vec<T> was added. Both were added a year after I added the Arc<Vec<u8>> APIs.

> PS: will you fix #92 to make it safe to read an FST from any slice lifetime?

Hmm. Maybe I wasn't being clear. Making Fst generic over AsRef<[u8]> will fix that, no?

**Comment by Kerollmops** [comment]
Yeah, sorry it is I am not an early morning guy :)

I think that the parametric type with `Arc<[u8]>` would fix that!
